version: 2.1

references:

  container_config: &container_config
    docker:
      - image: circleci/node:10.16

  load_repo: &load_repo
    restore_cache:
      key: v3-repo-{{ .Branch }}-{{ .Revision }}

  load_packages: &load_packages
    restore_cache:
      key: v3-modules-{{ .Branch }}-{{ .Revision }}

  load_build: &load_build
    restore_cache:
      key: v3-build-{{ .Branch }}-{{ .Revision }}

  load_coverage_results: &load_coverage_results
    restore_cache:
      key: v3-coverage-{{ .Branch }}-{{ .Revision }}

jobs:

  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Apply settings to use private registry
          command: ./infrastructure/githubpackages.sh
      - save_cache:
          key: v3-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
      - run: 
          name: Install Packages
          command: yarn --frozen-lockfile
      - save_cache:
          key: v3-modules-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project/node_modules
      - run: 
          name: Build Library
          command: yarn build
      - save_cache:
          key: v3-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project/lib
            - ~/project/dist

  test:
    <<: *container_config
    steps:
      - *load_repo
      - *load_packages
      - run:
          command: yarn test
          environment:
            JEST_JUNIT_OUTPUT: ./test-reports/unit/test-results.xml
      - store_test_results:
         path: ~/project/test-reports
      - save_cache:
          key: v3-coverage-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project/coverage

  coverage:
    <<: *container_config
    steps:
      - *load_repo
      - *load_packages
      - *load_coverage_results
      - run:
          command: yarn coverage

  publish:
    <<: *container_config
    steps:
      - *load_repo
      - *load_build
      - add_ssh_keys:
          fingerprints:
            - "f5:9f:74:b4:16:b7:1d:eb:ec:0d:0d:04:b1:83:26:b8"
      - run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          git config user.name bot-autopublish
          git config user.email info@malliapi.co.uk
          npm publish

workflows:
  build_test_deploy:
    jobs:
      - build:
          context: malliapi
      - test:
          context: malliapi
          requires:
            - build
      - coverage:
          context: malliapi
          requires:
            - test
          filters:
            branches:
              only: master
      - publish:
          context: malliapi
          requires:
            - build
            - test
          filters:
            branches:
              only: master
